version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ammg-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ammg
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ammg-network

  backend:
    build: ./backend
    container_name: ammg-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/ammg?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRE: 7d
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: /app/uploads
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongodb
    networks:
      - ammg-network

  frontend:
    build: ./frontend
    container_name: ammg-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - ammg-network

volumes:
  mongodb_data:
  uploads_data:

networks:
  ammg-network:
    driver: bridge
